<img align="left" src="https://lever-client-logos.s3.amazonaws.com/864372b1-534c-480e-acd5-9711f850815c-1524247202159.png" width=200>
<br></br>
<br></br>

# Neural Networks

## *Data Science Unit 4 Sprint 2 Assignment 1*

## Define the Following:
You can add image, diagrams, whatever you need to ensure that you understand the concepts below.

### Input Layer:

The input layer receives input from the dataset and is a visible layer since it is exposed and interacts with the data.  Typically there is one input node for each data element.

### Hidden Layer:

The hidden layer is not exposed directly to the data and consists of the weights and calculations used to to analyze the data.

### Output Layer:

The output later represents the results or output of the model.

### Neuron:

The real word biological cell that inspired the artificial neural network.

### Weight:

A value, or weight, applied to the data in the hidden layer.

### Activation Function:

An activation function decides how much signal to pass on to the next layer.  There are a variety of different functions such as sigmoid, tanh, step and relu that can be used depending on the use case.

### Node Map:

The node map is a visual representation of the topography of a neural network.

### Perceptron:

A simple neural network that takes input values, multiplies them by weights, sums the products, passes the sum through an activation function and outputs a final value.


## Inputs -> Outputs

### Explain the flow of information through a neural network from inputs to outputs. Be sure to include: inputs, weights, bias, and activation functions. How does it all flow from beginning to end?

Input is entered through input values, the values are multiplied by weights, a bias is added, the result is passed through an activation function and the final result is output.

## Write your own perceptron code that can correctly classify (99.0% accuracy) a NAND gate. 

| x1 | x2 | y |
|----|----|---|
| 0  | 0  | 1 |
| 1  | 0  | 1 |
| 0  | 1  | 1 |
| 1  | 1  | 0 |

In [1]:
import pandas as pd
data = { 'x1': [0,1,0,1],
         'x2': [0,0,1,1],
         'y':  [1,1,1,0]
       }

df = pd.DataFrame.from_dict(data).astype('int')
df

x1  x2  y
0   0   0  1
1   1   0  1
2   0   1  1
3   1   1  0

In [0]:
# The function np.exp(-x) is e**-x
def sigmoid(x):
  return 1 / (1 + np.exp(-x))

def sigmoid_derivate(x):
  sx = sigmoid(x)
  return sx * (1-sx)

In [3]:
import numpy as np
 
inputs = np.array([
                  [0, 0, 1],
                  [1, 0, 1],
                  [0, 1, 1],
                  [1, 1, 1]
])
inputs

array([[0, 0, 1],
       [1, 0, 1],
       [0, 1, 1],
       [1, 1, 1]])

In [4]:
correct_outputs = [[1], [1], [1], [0]]
correct_outputs

[[1], [1], [1], [0]]

In [5]:
weights = np.array([[1], [1], [-1.5]])
weights

array([[ 1. ],
       [ 1. ],
       [-1.5]])

In [6]:
weighted_sum = np.dot(inputs, weights)
weighted_sum

array([[-1.5],
       [-0.5],
       [-0.5],
       [ 0.5]])

In [7]:
activated_output = sigmoid(weighted_sum)
activated_output

array([[0.18242552],
       [0.37754067],
       [0.37754067],
       [0.62245933]])

In [8]:
error = correct_outputs - activated_output
error

array([[ 0.81757448],
       [ 0.62245933],
       [ 0.62245933],
       [-0.62245933]])

In [9]:
adjusted = error * sigmoid_derivate(activated_output)
adjusted

array([[ 0.2027025 ],
       [ 0.15019874],
       [ 0.15019874],
       [-0.1414639 ]])

In [10]:
weights += np.dot(inputs.T, adjusted)
weights

array([[ 1.00873484],
       [ 1.00873484],
       [-1.13836392]])

In [11]:
# Update our weights 10,000 times - (fingers crossed that this process reduces error)
for iteration in range(10000):
    
    # Weighted sum of inputs / weights
    weighted_sum = np.dot(inputs, weights)
    
    # Activate!
    activated_output = sigmoid(weighted_sum)
    
    # Calc error
    error = correct_outputs - activated_output
    
    adjustments = error * sigmoid_derivate(activated_output)
    
    # Update the Weights
    weights += np.dot(inputs.T, adjustments)
    
print("Weights after training")
print(weights)

print("Output after training")
print(activated_output)


Weights after training
[[-11.83730984]
 [-11.83730984]
 [ 17.80483027]]
Output after training
[[0.99999998]
 [0.9974457 ]
 [0.9974457 ]
 [0.0028158 ]]


## Implement your own Perceptron Class and use it to classify a binary dataset: 
- [The Pima Indians Diabetes dataset](https://raw.githubusercontent.com/ryanleeallred/datasets/master/diabetes.csv) 

You may need to search for other's implementations in order to get inspiration for your own. There are *lots* of perceptron implementations on the internet with varying levels of sophistication and complexity. Whatever your approach, make sure you understand **every** line of your implementation and what its purpose is.

In [12]:
diabetes = pd.read_csv('https://raw.githubusercontent.com/ryanleeallred/datasets/master/diabetes.csv')
diabetes.head()

Pregnancies  Glucose  BloodPressure  ...  DiabetesPedigreeFunction  Age  Outcome
0            6      148             72  ...                     0.627   50        1
1            1       85             66  ...                     0.351   31        0
2            8      183             64  ...                     0.672   32        1
3            1       89             66  ...                     0.167   21        0
4            0      137             40  ...                     2.288   33        1

[5 rows x 9 columns]

Although neural networks can handle non-normalized data, scaling or normalizing your data will improve your neural network's learning speed. Try to apply the sklearn `MinMaxScaler` or `Normalizer` to your diabetes dataset. 

In [0]:
from sklearn.preprocessing import MinMaxScaler, Normalizer

feats = list(diabetes)[:-1]

X = ...

In [14]:
##### Update this Class #####

class Perceptron(object):
    
    def __init__(self, niter = 10):
    self.niter = niter
    
    def __sigmoid(self, x):
        return None
    
    def __sigmoid_derivative(self, x):
        return None

    def fit(self, X, y):
    """Fit training data
    X : Training vectors, X.shape : [#samples, #features]
    y : Target values, y.shape : [#samples]
    """

    # Randomly Initialize Weights
    weights = ...

    for i in range(self.niter):
        # Weighted sum of inputs / weights

        # Activate!

        # Cac error

        # Update the Weights


    def predict(self, X):
    """Return class label after unit step"""
        return None

IndentationError: ignored

## Stretch Goals:

- Research "backpropagation" to learn how weights get updated in neural networks (tomorrow's lecture). 
- Implement a multi-layer perceptron. (for non-linearly separable classes)
- Try and implement your own backpropagation algorithm.
- What are the pros and cons of the different activation functions? How should you decide between them for the different layers of a neural network?